Repository colored-rs/colored, pull requests merged in 2023-12, with the labels that each got.

#86 Allow conversion from ColoredString to Error
  examples/as_error.rs
  src/error.rs
  src/lib.rs
Labels: bump-minor, needs-changelog

#149 Remove unnecessary is_terminal dependency
  .github/workflows/test.yml
  CHANGELOG.md
  Cargo.toml
  README.md
  src/control.rs
  src/lib.rs
Labels: bump-minor

#105 Handle possible errors in `set_virtual_terminal`
  CHANGELOG.md
  src/control.rs
Labels: needs-changelog

#153 feat: impl `From<(r, g, b)>` to `CustomColor`
  README.md
  examples/custom_colors.rs
  src/customcolors.rs
  src/lib.rs
Labels: bump-minor

#154 Add and Expose Methods of easily Creating and Mutating `ColoredString`'s and `Style`'s for Users
  CHANGELOG.md
  src/color.rs
  src/lib.rs
  src/style.rs
Labels: breaking
